/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.14.0
 *
 * Project: 'hello_rtt.release+DevKit-E7-HP' 
 * Target:  'release+DevKit-E7-HP' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "alif.h"

/* AlifSemiconductor::Device:SOC Peripherals:PINCONF@2.2.0 */
#define RTE_Drivers_LL_PINCONF              /* Driver PinPAD and PinMux */


#endif /* RTE_COMPONENTS_H */
