/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.7.0
 *
 * Project: 'hello_rtt.debug+HE' 
 * Target:  'debug+HE' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "alif.h"

/* AlifSemiconductor::CMSIS Driver:USART@1.3.0 */
#define RTE_Drivers_USART               /* Driver UART  */
/* AlifSemiconductor::Device:SOC Peripherals:GPIO@1.3.0 */
#define RTE_Drivers_GPIO              /* Driver GPIO */
/* AlifSemiconductor::Device:SOC Peripherals:PINCONF@1.3.0 */
#define RTE_Drivers_LL_PINCONF              /* Driver PinPAD and PinMux */


#endif /* RTE_COMPONENTS_H */
