/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.12.0+p48-gd3223e31
 *
 * Project: 'blinky.debug+DevKit-E8-HE' 
 * Target:  'debug+DevKit-E8-HE' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "alif.h"

/* AlifSemiconductor::Device:SOC Peripherals:GPIO@2.1.0 */
#define RTE_Drivers_IO              /* Driver GPIO */
/* AlifSemiconductor::Device:SOC Peripherals:PINCONF@2.1.0 */
#define RTE_Drivers_LL_PINCONF              /* Driver PinPAD and PinMux */


#endif /* RTE_COMPONENTS_H */
